### ISSUE TITLE
Airmode cannot load any interface

### ISSUE THREAD

**Issue by abueesp** [Frozenbox/airmode#2]
The button of "Reload wireless interfaces" on the configuration tab does not work.

I tried introducing manually the interface variable on "airmode_config.py". It says it is selecting the interface, but it does not appear on the menu. Also tried some minor changes like substituting `iwconfig 2>&1 | grep 802.11 | grep` by `iwconfig 2>&1 | grep 802.11` but nope.

If downloaded from Parrot repo instead of this one  we get[airmode_gui.py]:  `1169:        print ("Main_window.slot_reload_interfaces(): Not implemented yet")`

**Comment by abueesp** [comment]
Downloading directly from Parrot repo (I don't know why I cannot open issues there) it says:
airmode_gui.py
1169:        print ("Main_window.slot_reload_interfaces(): Not implemented yet")
And when the interface is selected manually, it does not verbose it was selected.

**Comment by PalinuroSec** [comment]
airmode is discontinued
